### ISSUE TITLE
Be able to install it with npm and import it as ES6 class

### ISSUE THREAD

**Issue by smcyr** [cferdinandi/bouncer#11]
I would like to install it with `npm install bouncer --save` and after that, import it like `import { Bouncer } from 'bouncer';`. Thanks!

**Comment by cferdinandi** [comment]
I don't currently support NPM for any of my open source projects, because I manage a few dozen of them and any additional step is something I'll typically forget to do with each update. It's a little thing, but it adds up.

**That said...** the new *GitHub Actions* feature (currently in beta) will automatically push to NPM if you want every time you push to GitHub. As soon as this is available, I'll add NPM support (since it removes my only resistance to supporting it).

Cheers!
