### ISSUE TITLE
Suggestions to the project

### ISSUE THREAD

**Issue by robsonsobral** [cferdinandi/bouncer#4]
There's some little things that can make easier for others to contribute to the project:

- to add an [editor config file](https://editorconfig.org/), so everybody can respect the code style easilly;
- to allow the use of the Gulp installed dependency as an option to developers who doesn't install it globally (like me);
- to add tests;
- to centralize changes on CHANGELOG.md.

**Comment by cferdinandi** [comment]
Thanks for these... great suggestions! Some quick thoughts...

> add an editor config file, so everybody can respect the code style easilly;

I like this idea, but...

There's an effort vs. benefit challenge with this one. The amount of detail needed for this file to be useful (and then the need to maintain it if codebase styles change) vs. the number of folks that actually contribute to these projects makes its benefit negligible and the cost of creating it high.

It's easier to just fix little things here and there manually, since almost no one submits PRs with version number updates so I need to run a build and repush anyways.

> allow the use of the Gulp installed dependency as an option to developers who doesn't install it globally (like me);

YES! Definitely. Migrating to Gulp 3 and updating the build process are on my todo list.

> add tests;

Also on the todo list. Currently wrestling with which testing platform to move forward with.

> centralize changes on CHANGELOG.md.

Probably won't be doing this. I maintain literally several dozen OSS projects, and even small added steps like this create work that ends up falling off the radar after a few releases.

I've found git tags (shown under the Releases tab) serve the same purpose and involve less effort on my part (since they're needed for CDN releases anyways... two birds, one stone)

**Comment by robsonsobral** [comment]
## the editor config file

I can't see any effort on creating one. It's just to fix the line endings and indentation. I prefer to use tabs, but I lost the battle and set my editor to use spaces. So, I had to replace all of them before to submit my PR.

## GULP

It's just a matter of add gulp to the `package.json` scritps:

```
"scripts": {
  "gulp": "gulp"
},
```

Anybody with Gulp installed globally, can run `gulp watch`. Other ones, like I did, can run `npm run gulp watch`. No need to update anything.

## Tests

I'm studying Jest and I'm really impressed. Fast and easy. I almost wrote an test for the pattern function before my PR, but had some problems at home to attend to.

## CHANGELOG

The file isn't to replace tags, but just to keep track of what changed and when. I also use tags. Every time I run the npm `version` command, a prescript adds the right tag and date to changelog file. I can write it, if you want to.

---

Also, the lock file is important to make sure everybody is running the same versions of dependencies. As it is automatically created, there's no extra effort.

**Comment by robsonsobral** [comment]
I'm preparing samples to show you!

Just two questions:

1. Are you sure you want to use tabs on `package.json`?
2. Why your files don't have a [empty line at their end](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)?

**Comment by robsonsobral** [comment]
Actually they do need an empty final line. Did you never saw the "No newline at end of file" warning on git? Diff and patch utilities complain about it a lot.

---

Ok! I made a sample of each suggestion! Each one on a different branch, if you want to accept a PR.

1. [editor config file](https://github.com/robsonsobral/bouncer/commit/2661d12717a2a1cbf05339e9052dedb89782b99b), to make collaborators editors (or yourself when editing away from your own computer) respect the same file edition standards;
2. [to make gulp locally available](https://github.com/robsonsobral/bouncer/commit/34cc36703888359891d21c4292ddd88e0535b1f4) and to add 2 common scripts alias;
3. add the [dependencies lock file](https://github.com/robsonsobral/bouncer/commit/e9fc96faa1653b1690fbaab80b7fc422d1cd3972) to make sure every contributor uses the same dependencies versions;
4. [add the changelog file](https://github.com/robsonsobral/bouncer/commit/a1143965459821f11705fbb0a7b7780375c4c189). Every run of `npm version SOMETHING` or `yarn version --SOMETHING` will move the unreleased section of changes to below a new one with the updated version number of `package.json` and date, before to add the git tag as usual.

**Comment by cferdinandi** [comment]
> Actually they do need an empty final line.

I know PHP files do for weird legacy server reasons. JS and CSS files? Not that I've ever seen. Never once gotten that warning.

**Comment by robsonsobral** [comment]
I've to confess there's so many time a saw this warning that I don't recall the situation.

**Comment by cferdinandi** [comment]
Moved to individual issues.
